### ISSUE TITLE
CPU Shares Error

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Daemon#3]
Setting CPU shares to 400 percent appears to break the daemon?

```
20:38:35.254Z ERROR pterodactyl.daemon: (server=7ab863c6-e857-4100-aeb7-e88219234343)
    HTTP code is 500 which indicates error: server error - Cannot start container 4a8b022b18e3: [8] System error: The maximum allowed cpu-shares is 262144

    --
    Error: HTTP code is 500 which indicates error: server error - Cannot start container 4a8b022b18e3: [8] System error: The maximum allowed cpu-shares is 262144

        at /srv/deamon/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:229:17
        at getCause (/srv/deamon/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:257:7)
        at Modem.buildPayload (/srv/deamon/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:228:5)
        at IncomingMessage.<anonymous> (/srv/deamon/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:204:14)
        at emitNone (events.js:72:20)
        at IncomingMessage.emit (events.js:166:7)
        at endReadableNT (_stream_readable.js:905:12)
        at doNTCallback2 (node.js:441:9)
        at process._tickDomainCallback (node.js:396:17)
```

**Comment by DaneEveritt** [comment]
I believe this was fixed in f2e52888ccaabb590048061972d60aa09c7878cc
