### ISSUE TITLE
Memory Leak in browser

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Daemon#8]
There appears to be a memory leak occurring that causes the panel's console page to just completely stop working when the server is started.

```
04:45:07.949Z  INFO pterodactyl.daemon: Server status has been changed to ON (server=deaecd3c-badb-4efe-a0a4-7aae48905c53)
04:45:21.258Z FATAL pterodactyl.daemon: (path=/server/power, method=PUT)
    SyntaxError: Unexpected end of input
        at Object.parse (native)
        at IncomingMessage.dockerTopStreamData (/srv/daemon/src/controllers/docker.js:214:38)
        at emitOne (events.js:90:13)
        at IncomingMessage.emit (events.js:182:7)
        at readableAddChunk (_stream_readable.js:147:16)
        at IncomingMessage.Readable.push (_stream_readable.js:111:10)
        at HTTPParser.parserOnBody (_http_common.js:109:22)
        at Socket.socketOnData (_http_client.js:315:20)
        at emitOne (events.js:90:13)
        at Socket.emit (events.js:182:7)
04:45:21.261Z FATAL pterodactyl.daemon: (path=/server/power, method=PUT)
    Error: Callback was already called.
        at /srv/daemon/node_modules/async/lib/async.js:43:36
        at /srv/daemon/node_modules/async/lib/async.js:723:17
        at /srv/daemon/node_modules/async/lib/async.js:167:37
        at Object.dockerTop [as callback] (/srv/daemon/src/controllers/docker.js:210:29)
        at /srv/daemon/node_modules/dockerode/lib/container.js:615:10
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:225:19)
        at ClientRequest.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:210:10)
        at emitOne (events.js:90:13)
        at ClientRequest.emit (events.js:182:7)
        at Socket.socketOnData (_http_client.js:320:9)
04:45:23.260Z FATAL pterodactyl.daemon: (path=/server/power, method=PUT)
    SyntaxError: Unexpected end of input
        at Object.parse (native)
        at IncomingMessage.dockerTopStreamData (/srv/daemon/src/controllers/docker.js:214:38)
        at emitOne (events.js:90:13)
        at IncomingMessage.emit (events.js:182:7)
        at readableAddChunk (_stream_readable.js:147:16)
        at IncomingMessage.Readable.push (_stream_readable.js:111:10)
        at HTTPParser.parserOnBody (_http_common.js:109:22)
        at Socket.socketOnData (_http_client.js:315:20)
        at emitOne (events.js:90:13)
        at Socket.emit (events.js:182:7)
04:45:23.262Z FATAL pterodactyl.daemon: (path=/server/power, method=PUT)
    Error: Callback was already called.
        at /srv/daemon/node_modules/async/lib/async.js:43:36
        at /srv/daemon/node_modules/async/lib/async.js:723:17
        at /srv/daemon/node_modules/async/lib/async.js:167:37
        at Object.dockerTop [as callback] (/srv/daemon/src/controllers/docker.js:210:29)
        at /srv/daemon/node_modules/dockerode/lib/container.js:615:10
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:225:19)
        at ClientRequest.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:210:10)
        at emitOne (events.js:90:13)
        at ClientRequest.emit (events.js:182:7)
        at Socket.socketOnData (_http_client.js:320:9)
04:45:23.263Z FATAL pterodactyl.daemon: (path=/server/power, method=PUT)
    SyntaxError: Unexpected end of input
        at Object.parse (native)
        at IncomingMessage.dockerTopStreamData (/srv/daemon/src/controllers/docker.js:214:38)
        at emitOne (events.js:90:13)
        at IncomingMessage.emit (events.js:182:7)
        at readableAddChunk (_stream_readable.js:147:16)
        at IncomingMessage.Readable.push (_stream_readable.js:111:10)
        at HTTPParser.parserOnBody (_http_common.js:109:22)
        at Socket.socketOnData (_http_client.js:315:20)
        at emitOne (events.js:90:13)
        at Socket.emit (events.js:182:7)
04:45:23.264Z FATAL pterodactyl.daemon: (path=/server/power, method=PUT)
    Error: Callback was already called.
        at /srv/daemon/node_modules/async/lib/async.js:43:36
        at /srv/daemon/node_modules/async/lib/async.js:723:17
        at /srv/daemon/node_modules/async/lib/async.js:167:37
        at Object.dockerTop [as callback] (/srv/daemon/src/controllers/docker.js:210:29)
        at /srv/daemon/node_modules/dockerode/lib/container.js:615:10
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:225:19)
        at ClientRequest.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:210:10)
        at emitOne (events.js:90:13)
        at ClientRequest.emit (events.js:182:7)
        at Socket.socketOnData (_http_client.js:320:9)
```

**Comment by DaneEveritt** [comment]
The crashing in the panel is most likely due to https://github.com/Pterodactyl/Panel/issues/38
