### ISSUE TITLE
TypeError: Cannot read property 'warn' of undefined

### ISSUE THREAD

**Issue by DDynamic** [Pterodactyl/Daemon#9]
```
22:00:48.181Z FATAL pterodactyl.daemon: (path=/server/power, method=PUT)
    TypeError: Cannot read property 'warn' of undefined
        at onFinished (/home/ddynamic/Workspaces/wings/daemon/src/controllers/docker.js:187:46)
        at Stream.onStreamError (/home/ddynamic/Workspaces/wings/daemon/node_modules/docker-modem/lib/modem.js:311:5)
        at emitOne (events.js:95:20)
        at Stream.emit (events.js:182:7)
        at Parser.parser.onError (/home/ddynamic/Workspaces/wings/daemon/node_modules/JSONStream/index.js:100:12)
        at Parser.proto.charError (/home/ddynamic/Workspaces/wings/daemon/node_modules/jsonparse/jsonparse.js:84:8)
        at Parser.proto.write (/home/ddynamic/Workspaces/wings/daemon/node_modules/jsonparse/jsonparse.js:112:23)
        at Stream.<anonymous> (/home/ddynamic/Workspaces/wings/daemon/node_modules/JSONStream/index.js:21:12)
        at Stream.stream.write (/home/ddynamic/Workspaces/wings/daemon/node_modules/through/index.js:26:11)
        at write (/home/ddynamic/Workspaces/wings/daemon/node_modules/docker-modem/node_modules/readable-stream/lib/_stream_readable.js:623:24)
22:00:48.188Z FATAL pterodactyl.daemon: (path=/server/power, method=PUT)
    Error: Callback was already called.
        at /home/ddynamic/Workspaces/wings/daemon/node_modules/async/lib/async.js:43:36
        at /home/ddynamic/Workspaces/wings/daemon/node_modules/async/lib/async.js:723:17
        at /home/ddynamic/Workspaces/wings/daemon/node_modules/async/lib/async.js:167:37
        at Object.dockerAttach [as callback] (/home/ddynamic/Workspaces/wings/daemon/src/controllers/docker.js:183:29)
        at /home/ddynamic/Workspaces/wings/daemon/node_modules/dockerode/lib/container.js:412:10
        at Modem.buildPayload (/home/ddynamic/Workspaces/wings/daemon/node_modules/docker-modem/lib/modem.js:225:19)
        at ClientRequest.<anonymous> (/home/ddynamic/Workspaces/wings/daemon/node_modules/docker-modem/lib/modem.js:210:10)
        at emitOne (events.js:90:13)
        at ClientRequest.emit (events.js:182:7)
        at Socket.socketOnData (_http_client.js:320:9)
```

**Comment by DaneEveritt** [comment]
`if (attachStreamErr) self.log.warn(attachStreamErr);` should be `if (attachStreamErr) self.server.log.warn(attachStreamErr);` on that line.

Thanks for the report, I'll get that fixed.

**Comment by DDynamic** [comment]
Pulled the latest, I get this now when I start a server:
```
{"name":"pterodactyl.daemon","hostname":"~STRIP~","pid":18942,"level":60,"path":"/server/power","method":"PUT","msg":"Error: Unexpected \"c\" at position 2 in state START\n    at Parser.proto.charError (/home/ddynamic/Workspaces/wings/daemon/node_modules/jsonparse/jsonparse.js:84:16)\n    at Parser.proto.write (/home/ddynamic/Workspaces/wings/daemon/node_modules/jsonparse/jsonparse.js:112:23)\n    at Stream.<anonymous> (/home/ddynamic/Workspaces/wings/daemon/node_modules/JSONStream/index.js:21:12)\n    at Stream.stream.write (/home/ddynamic/Workspaces/wings/daemon/node_modules/through/index.js:26:11)\n    at write (/home/ddynamic/Workspaces/wings/daemon/node_modules/docker-modem/node_modules/readable-stream/lib/_stream_readable.js:623:24)\n    at flow (/home/ddynamic/Workspaces/wings/daemon/node_modules/docker-modem/node_modules/readable-stream/lib/_stream_readable.js:632:7)\n    at HttpDuplex.pipeOnReadable (/home/ddynamic/Workspaces/wings/daemon/node_modules/docker-modem/node_modules/readable-stream/lib/_stream_readable.js:664:5)\n    at emitNone (events.js:80:13)\n    at HttpDuplex.emit (events.js:179:7)\n    at emitReadable_ (/home/ddynamic/Workspaces/wings/daemon/node_modules/docker-modem/node_modules/readable-stream/lib/_stream_readable.js:448:10)","time":"2016-02-05T00:20:49.141Z","v":0}
```

**Comment by DaneEveritt** [comment]
Can you parse that using the bunyan parser so that it is more readable, thanks.
